services:
  web:
    build: .
    ports:
      - "8080:8080"
    container_name: springboot-thymeleaf-app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
  
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: parcial
      MYSQL_USER: grupo_web
      MYSQL_PASSWORD: grupo_web
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
